# Generated by Django 4.1.6 on 2023-02-09 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('make', models.CharField(max_length=25)),
                ('model', models.CharField(max_length=25)),
                ('type', models.CharField(choices=[('BEV', 'Battery Electric Vehicle'), ('PHEV', 'Plug-In Hybrid Electric Vehicle'), ('HEV', 'Hybrid Electric Vehicle'), ('FCEV', 'Fuel Cell Electric Vehicle')], default='BEV', max_length=4, verbose_name='EV Type')),
                ('batterysize', models.IntegerField()),
            ],
        ),
    ]
