# Generated by Django 4.1.6 on 2023-02-07 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='station',
            old_name='location',
            new_name='address',
        ),
        migrations.RenameField(
            model_name='station',
            old_name='connector',
            new_name='connectors',
        ),
        migrations.RenameField(
            model_name='station',
            old_name='review',
            new_name='reviews',
        ),
    ]
