# Generated by Django 4.1.6 on 2023-02-17 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_alter_vehicle_make_alter_vehicle_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='batterysize',
            field=models.IntegerField(verbose_name='Battery Size'),
        ),
    ]
