# Generated by Django 4.1.6 on 2023-02-07 17:56

from django.db import migrations, models
import django.db.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_alter_station_reviews'),
    ]

    operations = [
        migrations.AlterField(
            model_name='station',
            name='reviews',
            field=models.TextField(max_length=200, verbose_name=django.db.models.fields.TextField),
        ),
    ]
